# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('box', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='.')),
                ('num_panels', models.IntegerField(default=4)),
                ('text_pos', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='Top', max_length=10)),
                ('share', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
