# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-24 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170112_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gif',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
